name: Unit Test Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.2"

      - name: Set Environment Variables
        run: |
            echo "MODE=dev" >> $GITHUB_ENV
            echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements.txt
          pip install -r ${{ github.workspace }}/test_requirements.txt
      - name: Run tests
        run: |
          python -m pytest --cov=${{ github.workspace }}/src ${{ github.workspace }}/tests/units